/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ieee_802_15_4_python
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_IEEE_802_15_4_PYTHON_API_H
#define INCLUDED_IEEE_802_15_4_PYTHON_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ieee_802_15_4_python_EXPORTS
#define IEEE_802_15_4_PYTHON_API __GR_ATTR_EXPORT
#else
#define IEEE_802_15_4_PYTHON_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_IEEE_802_15_4_PYTHON_API_H */
